<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Room;

class RoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Room::insert([
            [
                'name_ar' => 'غرفة ديلوكس',
                'name_en' => 'Deluxe Room',
                'description_ar' => 'غرفة ديلوكس مع إطلالة رائعة على البحر.',
                'description_en' => 'Deluxe room with a beautiful sea view.',
                'space' => 50,
                'allowed_persons' => 2,
                'availability' => 1,
                'view' => true,
                'bathroom' => true,
                'kitchen' => false,
                'tv' => true,
                'air_condition' => true,
                'wifi' => true,
                'smoke' => false,
                'disabled' => false,
                'king_bed' => 1,
                'single_bed' => 0,
                'sofa_bed' => 1,
                'night_price' => 120.00,
                'discount_price' => 100.00,
                'bathroom_details_ar' => json_encode(['دش', 'حوض استحمام']),
                'bathroom_details_en' => json_encode(['Shower', 'Bathtub']),
                'kitchen_details_ar' => null,
                'kitchen_details_en' => null,
                'preparations_ar' => json_encode(['منشفة', 'مجفف شعر']),
                'preparations_en' => json_encode(['Towel', 'Hair Dryer']),
                'media_tech_ar' => json_encode(['تلفزيون', 'واي فاي']),
                'media_tech_en' => json_encode(['TV', 'Wi-Fi']),
                'image' => 'deluxe_room.jpg',
                'alt_images' => json_encode(['deluxe_room_alt1.jpg', 'deluxe_room_alt2.jpg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_ar' => 'غرفة عائلية',
                'name_en' => 'Family Room',
                'description_ar' => 'غرفة عائلية مريحة تناسب جميع أفراد الأسرة.',
                'description_en' => 'Comfortable family room suitable for all family members.',
                'space' => 80,
                'allowed_persons' => 4,
                'availability' => 1,
                'view' => true,
                'bathroom' => true,
                'kitchen' => true,
                'tv' => true,
                'air_condition' => true,
                'wifi' => true,
                'smoke' => false,
                'disabled' => false,
                'king_bed' => 1,
                'single_bed' => 2,
                'sofa_bed' => 1,
                'night_price' => 200.00,
                'discount_price' => 180.00,
                'bathroom_details_ar' => json_encode(['دش', 'حوض مزدوج']),
                'bathroom_details_en' => json_encode(['Shower', 'Double Sink']),
                'kitchen_details_ar' => json_encode(['ثلاجة', 'ميكروويف']),
                'kitchen_details_en' => json_encode(['Fridge', 'Microwave']),
                'preparations_ar' => json_encode(['مجفف شعر', 'مناشف إضافية']),
                'preparations_en' => json_encode(['Hair Dryer', 'Extra Towels']),
                'media_tech_ar' => json_encode(['تلفزيون', 'نظام صوت']),
                'media_tech_en' => json_encode(['TV', 'Sound System']),
                'image' => 'family_room.jpg',
                'alt_images' => json_encode(['family_room_alt1.jpg', 'family_room_alt2.jpg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name_ar' => 'جناح رجال الأعمال',
                'name_en' => 'Business Suite',
                'description_ar' => 'جناح خاص لرجال الأعمال.',
                'description_en' => 'Exclusive suite for business travelers.',
                'space' => 60,
                'allowed_persons' => 2,
                'availability' => 1,
                'view' => true,
                'bathroom' => true,
                'kitchen' => false,
                'tv' => true,
                'air_condition' => true,
                'wifi' => true,
                'smoke' => false,
                'disabled' => true,
                'king_bed' => 1,
                'single_bed' => 0,
                'sofa_bed' => 0,
                'night_price' => 150.00,
                'discount_price' => 130.00,
                'bathroom_details_ar' => json_encode(['دش', 'مناشف فاخرة']),
                'bathroom_details_en' => json_encode(['Shower', 'Luxury Towels']),
                'kitchen_details_ar' => null,
                'kitchen_details_en' => null,
                'preparations_ar' => json_encode(['مكتب', 'كرسي مريح']),
                'preparations_en' => json_encode(['Desk', 'Comfortable Chair']),
                'media_tech_ar' => json_encode(['تلفزيون', 'انترنت عالي السرعة']),
                'media_tech_en' => json_encode(['TV', 'High-Speed Internet']),
                'image' => 'business_suite.jpg',
                'alt_images' => json_encode(['business_suite_alt1.jpg', 'business_suite_alt2.jpg']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Additional room records go here
        ]);
    }
}
